site_name: "DevUniversity DevOps Bootcamp 202309: FastAPI-Traefik-K8s"
#site_url: https://devops-boot.github.com/fastapi-k8s/
repo_url: https://github.com/devops-boot/fastapi-k8s/
site_description: "Project Documentation for FastAPI-Traefik-K8s Team during DevUniversity DevOps Bootcamp 202309"
#site_author: ""
#copyright:
#remote_branch: ""
#remote_name: ""
nav:
  - Home: index.md
  - Project: project.md
  - Documentation: documentation.md
exclude_docs: |
  .placeholder
#not_in_nav:
theme:
  name: material
  locale: en
#site_dir: "site"
use_directory_urls: true
markdown_extensions:
  - extra
  - admonition
  - codehilite
  - meta
  - nl2br
  - sane_lists
  - smarty
  - toc
  - wikilinks
  - markdown_include.include:
      base_path: docs  # - markdown_include.include:
  #     base_path: .
plugins:
  - search:
      separator: '[\s\-\.\_]+'
  # - mkdocstrings:
  #     handlers:
  #       # See: https://mkdocstrings.github.io/python/usage/
  #       python:
  #         options:
  #           # Possible styles are sphinx, google, or numpy
  #           docstring_style: sphinx
