kind: "postgresql"
apiVersion: "acid.zalan.do/v1"
metadata:
  name: "fastapi-db"
  namespace: {{ .Values.namespace }}
  labels:
    team: acid
spec:
  teamId: "acid"
  postgresql:
    version: "15"
  numberOfInstances: 3
  enableMasterLoadBalancer: false
  enableReplicaLoadBalancer: false
  volume:
    size: "10Gi"
    storageClass: "ebs-sc"
  users:
    fastapi_traefik:
      - superuser
      - createdb
  allowedSourceRanges:
    - 10.0.0.0/16
  databases:
    fastapi_traefik: fastapi_traefik
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 500m
      memory: 500Mi
