apiVersion: v1
kind: ConfigMap
metadata:
  name: pod-config
data:
  # Backup definition
  WAL_S3_BUCKET: devops-boot-s3backup
  WAL_BUCKET_SCOPE_PREFIX: ""
  WAL_BUCKET_SCOPE_SUFFIX: ""
  USE_WALG_BACKUP: "true"
  USE_WALG_RESTORE: "true"
  BACKUP_SCHEDULE: '00 12 * * *'
  AWS_ACCESS_KEY_ID: {{ .Values.s3_backup_aws_access_key_id }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.s3_backup_aws_secret_access_key }}
  AWS_REGION: us-east-1
  WALG_DISABLE_S3_SSE: "true"
  BACKUP_NUM_TO_RETAIN: "5"

  # Auto restore at cluster initiation
  CLONE_USE_WALG_RESTORE: "true"
  CLONE_AWS_ACCESS_KEY_ID: {{ .Values.s3_backup_aws_access_key_id }}
  CLONE_AWS_SECRET_ACCESS_KEY: {{ .Values.s3_backup_aws_secret_access_key }}
  CLONE_AWS_REGION: us-east-1
  CLONE_METHOD: CLONE_WITH_WALE
  CLONE_WAL_BUCKET_SCOPE_PREFIX: ""
  CLONE_WAL_S3_BUCKET: devops-boot-s3backup
