# values.yaml
# Special settings for traefik running in EKS
# https://traefik.io/blog/eks-clusters-with-traefik-proxy-as-the-ingress-controller/
---
apiVersion: networking.k8s.io/v1
kind: IngressClass
ingressClass:
  enabled: true
  isDefaultClass: true
  fallbackApiVersion: v1
ingressRoute:
  dashboard:
    enabled: false
service:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
globalArguments:
- "--api.insecure=true"