# Namespace
namespace: "dev"

ingress:
  name: "ingress"
  fastapiHostname: "fastapi.localhost"

# FastAPI app variables
fastapiApp:
  replicas: 3
  name: "fastapi-app"
  image: "dockerkvark/fastapi_app:v5"
  containerPort: 8000
  env:
    DATABASE_URL: "postgresql://fastapi_traefik:fastapi_traefik@postgres-service:5432/fastapi_traefik"

fastapiService:
  name: "fastapi-service"

fastapiHpa:
  name: "fastapi-hpa"
  minReplicas: 3
  maxReplicas: 6
  averageUtilization: 70

# Postgres variables

postgresDb:
  name: "postgres-db"
  image: "postgres:12.0-alpine"

postgresConfig:
  name: "postgres-config"
  POSTGRES_USER: fastapi_traefik
  POSTGRES_PASSWORD: fastapi_traefik
  POSTGRES_DB: fastapi_traefik

postgresPv:
  name: "postgres-pv"
  storage: 10Gi
  path: "/mnt/data"

postgresPvc:
  name: "postgres-pvc"

postgresService:
  name: "postgres-service"

clusterIssuer:
  name: "cluster-issuer"
  email: "github@kvark.fr"
  server: "https://acme-staging-v02.api.letsencrypt.org/directory" # staging server
  privateKeySecretRef:
    name: "letsencrypt-staging"
