apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: monitoring-ingress
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Values.ingress.name }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.clusterIssuer.name }}
spec:
  ingressClassName: traefik
  tls:
    - secretName: monitoring-ingress-secret
      hosts:
        - {{ .Values.ingress.grafanaHostname }}
        - {{ .Values.ingress.prometheusHostname }}
  rules:
    - host: {{ .Values.ingress.grafanaHostname }}
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: {{ .Values.grafanaService.name }}
                port:
                  number: 80
    - host: {{ .Values.ingress.prometheusHostname }}
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: {{ .Values.prometheusService.name }}
                port:
                  number: 9090
