# https://developer.hashicorp.com/terraform/tutorials/automation/github-actions

name: "Terraform Deploying Preprod Apply"

on:
  push:
    branches:
      - main
    paths:
      - "terraform/deployments/preprod/**"
      - ".github/workflows/terraform_deployments_preprod_apply.yaml"
  workflow_dispatch:

env:
  TF_CLOUD_ORGANIZATION: "devops-boot"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_WORKSPACE: "deployments-preprod"
  CONFIG_DIRECTORY: "./"

jobs:
  terraform:
    name: "Terraform Deploying Preprod Apply"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload Configuration
        uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.1.1
        id: apply-upload
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          directory: ${{ env.CONFIG_DIRECTORY }}

      - name: Create Apply Run
        uses: hashicorp/tfc-workflows-github/actions/create-run@v1.1.1
        id: apply-run
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          configuration_version: ${{ steps.apply-upload.outputs.configuration_version_id }}

      - name: Apply
        uses: hashicorp/tfc-workflows-github/actions/apply-run@v1.1.1
        if: fromJSON(steps.apply-run.outputs.payload).data.attributes.actions.IsConfirmable
        id: apply
        with:
          run: ${{ steps.apply-run.outputs.run_id }}
          comment: "Apply Run from GitHub Actions CI ${{ github.sha }}"
